name: env-ids
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pandas>=2.0
  - jupyter
  - ipykernel
  - nltk
  - gensim
  - numpy
  - scipy=1.12
  - scikit-learn
  - mlxtend
  - nltk
  - umap-learn
  - sktime
  - statsmodels
  - pmdarima
  - matplotlib
  - seaborn
  - plotly
  - graphviz
  - networkx
  - pip
  - pip:
      - pm4py==2.7.*
      - p_decision_tree
      - mrjob
      - kaleido
